sudo: required
services:
  - docker

before_install:
  - docker build -t ysahakyan1998/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ysahakyan1998/react-test npm test

after_success:
  - docker build -t ysahakyan1998/multi-nginx ./nginx
  - docker build -t ysahakyan1998/multi-server ./server
  - docker build -t ysahakyan1998/multi-worker ./worker
  - docker build -t ysahakyan1998/multi-client ./client
  # Login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take above images and push to docker-hub
  - docker push ysahakyan1998/multi-nginx
  - docker push ysahakyan1998/multi-server
  - docker push ysahakyan1998/multi-worker
  - docker push ysahakyan1998/multi-client
